version: "3"
services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: infrastructure-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./data/minio:/data
    env_file: .env
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:?}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:?}
    networks:
      - s3

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: infrastructure-zookeeper
    env_file: .env
    environment:
      - ZOOKEEPER_CLIENT_PORT=${ZOOKEEPER_CLIENT_PORT:?}
      - ZOOKEEPER_TICK_TIME=${ZOOKEEPER_TICK_TIME:?}
    networks:
      - kafka

  broker:
    image: confluentinc/cp-kafka:latest
    container_name: infrastructure-kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    env_file: .env
    environment:
      - KAFKA_BROKER_ID=${KAFKA_BROKER_ID:?}
      - KAFKA_ZOOKEEPER_CONNECT=${KAFKA_ZOOKEEPER_CONNECT:?}
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:?}
      - KAFKA_ADVERTISED_LISTENERS=${KAFKA_ADVERTISED_LISTENERS:?}
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:?}
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR:?}
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR:?}
    networks:
      - kafka

  postgres:
    image: "postgres:15-alpine"
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME:?}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
      - POSTGRES_DB=${POSTGRES_DATABASE:?}
    networks:
      - postgres

  redis:
    image: "redis:7.2.1-alpine"
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/d–∞ta:/root/redis
      - ./data/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    env_file: .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:?}
    networks:
      - redis

  account:
    build:
      context: .
      dockerfile: ./../account/Dockerfile
    container_name: account
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
      - broker
      - minio
    ports:
      - "8010:8010"
    env_file: ./../account/.env
    networks:
      - services
      - postgres
      - redis
      - s3
      - kafka

networks:
  services:
    driver: bridge
  postgres:
    driver: bridge
  redis:
    driver: bridge
  s3:
    driver: bridge
  kafka:
    driver: bridge
